### Importing the libraries

# Artificial Neural Network

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.8.2'

## Part 1 - Data Preprocessing

### Importing the dataset

In [25]:
dataset = pd.read_csv("Churn_Modelling.csv")
X = dataset.iloc[:, 3:-1].values
Y = dataset.iloc[:, -1].values

In [26]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [27]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [28]:
print(Y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [29]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:, -2])


In [30]:
print(X)

[[619 'France' 1 ... 1 1 101348.88]
 [608 'Spain' 1 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 1 ... 0 1 42085.58]
 [772 'Germany' 0 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [37]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder 
ct = ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [1])], remainder="passthrough")
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 1.0 ... 1 1 101348.88]
 [1.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 1.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 1.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 1.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

### Feature Scaling

In [33]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [15]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [19]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))  # Dense = 은닉층에 숨길 뉴런의 개수를 결정, activation = 활성화 함수의 종류를 결정


### Adding the second hidden layer

In [20]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

### Adding the output layer

In [22]:
ann.add(tf.keras.layers.Dense(units=1, activation="sigmoid")) # 출력값이 이진 변수이기 때문에 단위 매개 변수를 1로 설정

## Part 3 - Training the ANN

### Compiling the ANN

In [23]:
ann.compile(optimizer="adam", loss="binary_crossentropy" , metrics=["accuracy"] )
# 이진범수를 예측한다면 손실함수는 binary_crossentropy, 범주화 변수는 손실함수를 categorical_entropy를 설정해줘야 한다

훈련 과정에서 optimizer를 통해 비용함수를 최적화하면 이 과정에서 loss를 통해 최소화 하는것이 목적이다. 이 과정에서 matrics가 사용되는데 한마디로 이 모델의 성능평가라 볼 수 있다

### Training the ANN on the Training set

In [24]:
ann.fit(X_train, Y_train, batch_size= 32, epochs=100) # 한번의 하나의 행을 계산하기 보다는 배치 사이즈를 설정해 훈련시키는게 효율적이다

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5641 - accuracy: 0.7385
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4509 - accuracy: 0.7995
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4328 - accuracy: 0.8121
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4198 - accuracy: 0.8249
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4101 - accuracy: 0.8325
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4018 - accuracy: 0.8378
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3925 - accuracy: 0.8400
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3800 - accuracy: 0.8454
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3691 - accuracy: 0.8475
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3615 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

In [57]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))
# 고객이 은행을 떠날 확률은 3프로 정도로 매우 희박하다

[[0.03571591]]


1. 정보는 쌍 대괄호로 2d 배열로 입력한다
2. 범주형 변수에 더미 변수를 입력해야 한다
3. 동일한 feature Scaling 과정을 거쳐야 한다

### Predicting the Test set results

In [59]:
Y_pred = ann.predict(X_test)
Y_pred = (Y_pred > 0.5)
print(np.concatenate((Y_pred.reshape(len(Y_pred), 1), Y_test.reshape(len(Y_test), 1)), 1))
# 왼쪽에는 예측벡터, 오른쪽에는 실제 벡터

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [60]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)
# 86프로의 정확도로 훌륭한 효율을 보인다

[[1532   63]
 [ 205  200]]


0.866